export const ipcChannels = {
  describeSidecarCapabilities: 'sidecar:describe-capabilities',
  refreshSidecarCapabilities: 'sidecar:refresh-capabilities',
  loadWorkspace: 'workspace:load',
  addProject: 'workspace:add-project',
  removeProject: 'workspace:remove-project',
  refreshProjectGitContext: 'projects:refresh-git-context',
  savePattern: 'patterns:save',
  deletePattern: 'patterns:delete',
  setPatternFavorite: 'patterns:set-favorite',
  createSession: 'sessions:create',
  duplicateSession: 'sessions:duplicate',
  renameSession: 'sessions:rename',
  setSessionPinned: 'sessions:set-pinned',
  setSessionArchived: 'sessions:set-archived',
  sendSessionMessage: 'sessions:send-message',
  querySessions: 'sessions:query',
  updateScratchpadSessionConfig: 'sessions:update-scratchpad-config',
  selectProject: 'selection:project',
  selectPattern: 'selection:pattern',
  selectSession: 'selection:session',
  workspaceUpdated: 'workspace:updated',
  sessionEvent: 'sessions:event',
} as const;
